### ISSUE TITLE
This plugin fails with webpack 2.1.0-beta.20

### ISSUE THREAD

**Issue by sebastiandeutsch** [shaketbaby/directory-named-webpack-plugin#2]
I'm in the progress of updating my [boilerplate](https://github.com/sebastiandeutsch/react-redux-starter) to webpack 2. Unfortunately the plugin doesn't work anymore:

```
> ReactReduxBoilerplate@0.0.1 start /Users/sebastiandeutsch/development/node/react-redux-starter
> node server.js

/Users/sebastiandeutsch/development/node/react-redux-starter/webpack/config.development.js:18
    new webpack.ResolverPlugin(new DirectoryNamedWebpackPlugin()),
    ^

TypeError: webpack.ResolverPlugin is not a constructor
    at Object.<anonymous> (/Users/sebastiandeutsch/development/node/react-redux-starter/webpack/config.development.js:18:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sebastiandeutsch/development/node/react-redux-starter/server.js:4:14)
    at Module._compile (module.js:541:32)
```

As far as I understood this [issue](https://github.com/webpack/webpack/issues/2324) `resolve` got a new property `resolve.plugins` and `webpack.ResolverPlugin` is deprecated. But I didn't manage to get it running.

When I tried to investigate I found the [CloneBasenamePlugin](https://github.com/webpack/enhanced-resolve/blob/master/lib/CloneBasenamePlugin.js) which, from analysing the [test](https://github.com/webpack/enhanced-resolve/blob/d154f01b6f74b90f3ac3c5ea6cca89abead5236c/test/plugins.js), actually does what this plugin is doing. 

Unfortunately I was not able to get it running as well - maybe you have an idea.

**Comment by sebastiandeutsch** [comment]
I've actually managed to fix it for Webpack 2. Is this repository still maintained or shall I release it as a new plugin?

**Comment by shaketbaby** [comment]
Sorry, didn't get an notificatio for this issue so wasn't aware until now. Since you already have the fix, do you mind to create a PR for that? Thanks!

**Comment by sebastiandeutsch** [comment]
Since you didn't respond I released it as a new plugin: https://github.com/sebastiandeutsch/component-directory-webpack-plugin I've also added a few tests. Feel free to adapt for your plugin.

**Comment by sebastiandeutsch** [comment]
PS: There is no official way to probe for the webpack version so you should adapt your package.json to make sure a developer knows that the current version of your plugin won't work with webpack 2.

**Comment by shaketbaby** [comment]
Thanks, will do that.
